---
# tasks file for php
- name: "[VARS] Load OS-Specific Variables"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: 
  - php
  - configs

- name: "[INSTALL] RedHat Setup"
  include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: 
  - php

- name: "[INSTALL] Debian Setup"
  include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags: 
  - php

- name: "[GENERATE] Apache php.conf"
  sudo: yes
  template: src=php.ini.j2 dest=/etc/php.ini owner=root group=root mode=644
  tags:
  - php

- name: "[GENERATE] PHP.ini"
  sudo: yes
  template: src=php.ini.j2 dest=/etc/php.ini owner=root group=root mode=644
  tags:
  - php